feat(tsx): added support for tsx
fossology/Nirjas pull request #23
Opened 2020-12-13 04:15 UTC by Aman-Codes

Added support for tsx
Part of #18

2020-12-14 07:55 UTC, GMishx requested changes

2020-12-14 07:55 UTC, GMishx commented on testScript.py
> +        "https://raw.githubusercontent.com/microsoft/TypeScript/master/tests/cases/user/formik/index.tsx"
Can you please refer to a specific commit rather than `master`?
```suggestion
        "https://raw.githubusercontent.com/microsoft/TypeScript/c33a14d66d0a452673ce77256e178bf84e875d2b/tests/cases/user/formik/index.tsx"
```

2020-12-14 08:04 UTC, Aman-Codes commented on testScript.py
> +        "https://raw.githubusercontent.com/microsoft/TypeScript/master/tests/cases/user/formik/index.tsx"
@GMishx Did the asked changes

2020-12-15 06:21 UTC, GMishx commented on testScript.py
>          "https://raw.githubusercontent.com/airbnb/react-with-styles/2532394bb866aaade4dc750ee94c0ff213d9b6de/src/withStyles.jsx"
Appears to be a duplicate entry. Please remove one of the `withStyles.jsx` file.

2020-12-15 06:54 UTC, Aman-Codes commented on testScript.py
>          "https://raw.githubusercontent.com/airbnb/react-with-styles/2532394bb866aaade4dc750ee94c0ff213d9b6de/src/withStyles.jsx"
@GMishx Did the change

2020-12-15 09:13 UTC, GMishx commented
Hi @Aman-Codes , can you please rebase? There are new merge conflicts.

2020-12-15 09:19 UTC, Aman-Codes commented
Hi @GMishx 
I am trying to do the same just facing some issue.

2020-12-15 09:38 UTC, GMishx commented
Oh, sorry I didn't notice that. If you need any help, please feel free to ping me on Slack.

2020-12-15 13:05 UTC, Aman-Codes commented
@GMishx I finally resolved all the conflicts! Kindly review this

2020-12-17 08:01 UTC, GMishx approved these changes

2020-12-17 08:02 UTC, merged