Added support for Julia language
fossology/Nirjas pull request #52
Opened 2021-12-05 07:58 UTC by soham4abc

Fixes #34 

Please can anyone help me or guide me to let me know where my tests are failing?

@GMishx @Kaushl2208

2021-12-06 11:52 UTC, Kaushl2208 commented
> Fixes #34
> 
> Please can anyone help me or guide me to let me know where my tests are failing?
> 
> @GMishx @Kaushl2208

You need to change the testfile:
1. The current test file contains the unicode characters.
2. Run Nirjas on the same testfile and analyse the output and share it here as well(the output).

2021-12-11 05:44 UTC, soham4abc commented
```
PS C:\Users\SOHAM\Desktop\misc\tempnirjas> nirjas .\test.jl
{
    "metadata": {
        "filename": ".\\test.jl",
        "lang": "Julia",
        "total_lines": 75,
        "total_lines_of_comments": 8,
        "blank_lines": 16,
        "sloc": 51
    },
    "single_line_comment": [
        {
            "line_number": 5,
            "comment": "get the category, don't process some files"
        },
        {
            "line_number": 15,
            "comment": "process the  lines"
        },
        {
            "line_number": 23,
            "comment": "handle subcategories"
        },
        {
            "line_number": 27,
            "comment": "collect repo info"
        },
        {
            "line_number": 56,
            "comment": "-----------------------------------------------------------------"
        },
        {
            "line_number": 61,
            "comment": "loop over all markdown files in the root directory, appending the records to the list"
        },
        {
            "line_number": 67,
            "comment": "save a csv file"
        },
        {
            "line_number": 75,
            "comment": "module"
        }
    ],
    "cont_single_line_comment": [],
    "multi_line_comment": []
}
PS C:\Users\SOHAM\Desktop\misc\tempnirjas>
```

2021-12-11 05:46 UTC, soham4abc commented
This is what I get when I am running the same test file using nirjas. What I need to change? @Kaushl2208 

> ```
> PS C:\Users\SOHAM\Desktop\misc\tempnirjas> nirjas .\test.jl
> {
>     "metadata": {
>         "filename": ".\\test.jl",
>         "lang": "Julia",
>         "total_lines": 75,
>         "total_lines_of_comments": 8,
>         "blank_lines": 16,
>         "sloc": 51
>     },
>     "single_line_comment": [
>         {
>             "line_number": 5,
>             "comment": "get the category, don't process some files"
>         },
>         {
>             "line_number": 15,
>             "comment": "process the  lines"
>         },
>         {
>             "line_number": 23,
>             "comment": "handle subcategories"
>         },
>         {
>             "line_number": 27,
>             "comment": "collect repo info"
>         },
>         {
>             "line_number": 56,
>             "comment": "-----------------------------------------------------------------"
>         },
>         {
>             "line_number": 61,
>             "comment": "loop over all markdown files in the root directory, appending the records to the list"
>         },
>         {
>             "line_number": 67,
>             "comment": "save a csv file"
>         },
>         {
>             "line_number": 75,
>             "comment": "module"
>         }
>     ],
>     "cont_single_line_comment": [],
>     "multi_line_comment": []
> }
> PS C:\Users\SOHAM\Desktop\misc\tempnirjas>
> ```

2022-01-03 11:54 UTC, Kaushl2208 commented on nirjas/languages/tests/test_julia.py
> +                "lang": "julia",
```suggestion
                "lang": "Julia",
```

2022-01-03 11:56 UTC, soham4abc commented
All Checks passed @Kaushl2208  PTAL

2022-01-03 11:57 UTC, Kaushl2208 requested changes

2022-01-03 11:57 UTC, Kaushl2208 commented on nirjas/languages/julia.py
> +Kaushlendra Pratap (kaushlendrapratap.9837@gmail.com)
You should change the copyright to your name.

2022-01-03 11:57 UTC, Kaushl2208 commented on testScript.py
> +        "https://raw.githubusercontent.com/svaksha/Julia.jl/master/src/scrape.jl"
Change master ==> to a persistent commit id, As the changes in the master will usually get lost.

2022-01-03 12:07 UTC, soham4abc commented
All requested changes done PTAL @Kaushl2208

2022-01-04 04:30 UTC, soham4abc commented
Any more changes required @GMishx  @Kaushl2208 ??

2022-01-04 04:42 UTC, Kaushl2208 approved these changes
Changes LGTM, Needs test!

2022-01-04 12:47 UTC, soham4abc commented
> Changes LGTM, Needs test!

Nice... Let me know if any more changes are required!

2022-01-06 07:34 UTC, soham4abc commented
Any changes required? @Kaushl2208

2022-01-10 07:09 UTC, soham4abc commented
> Any changes required? @Kaushl2208
@Kaushl2208  @GMishx ??

2022-01-11 04:13 UTC, Kaushl2208 commented
Hey @soham4abc , We will let you know once the testing has been completed for the PR.

Thankyou for your patience. :)

2022-01-11 20:19 UTC, Kaushl2208 commented
Hey  @soham4abc , I have tested it. Thankyou for your contributions.


CC: @GMishx

2022-01-12 04:09 UTC, soham4abc commented
> Hey @soham4abc , I have tested it. Thankyou for your contributions.
> 
> Can you Squash the commits into one before I merge it? CC: @GMishx

changes merged to one commit and rebased

2022-01-12 14:15 UTC, merged