Sushant added sql
fossology/Nirjas pull request #55
Opened 2021-12-20 14:17 UTC by its-sushant

pull request for #37

2021-12-21 06:19 UTC, Kaushl2208 requested changes
Hey, Can you add the test data file as a raw github content link. On which your test will run on.

2021-12-21 16:55 UTC, Kaushl2208 commented
Hey @its-sushant , You have few whitespaces in sql and main file! 
Try and remove it

2021-12-21 17:34 UTC, its-sushant commented
> Hey @its-sushant , You have few whitespaces in sql and main file! Try and remove it

Ok, I will try to remove it..

2021-12-22 11:23 UTC, GMishx requested changes

2021-12-22 11:23 UTC, GMishx commented on source.txt
> +import { ThriftTest } from "./gen-js/ThriftTest_types";
Please remove invalid files from the commit.

2021-12-22 12:10 UTC, its-sushant commented on source.txt
> +import { ThriftTest } from "./gen-js/ThriftTest_types";
Ok i will remove that

2022-01-03 11:49 UTC, Kaushl2208 approved these changes
Changes Looks good! Needs test.

2022-01-11 20:26 UTC, Kaushl2208 commented
Hey @its-sushant , Thankyou for your contributions. I have tested it

CC: @GMishx

2022-01-11 20:30 UTC, merged